### ISSUE TITLE
Sequences size

### ISSUE THREAD

**Issue by KooroshRH** [wangkaihong/Unsup_Recycle_GAN#13]
Hi,

I asked some questions about the structure of the dataset before, but I forgot to ask about the sequence size that you used for the A and B domains while training. You mentioned the amounts of epochs for a reasonably good training, but it would be better to know the size of sequences.

Thanks a lot

**Comment by wangkaihong** [comment]
If i understand your question correctly, we do not require the input data to be organized into sequences as precedent works do. So each image are sent to the training individually.

**Comment by KooroshRH** [comment]
So do you mean that you put all viper frames in A folder and all cityscapes frames in B?
I want to use this model for translation between viper domains like snow, rain and night.

**Comment by wangkaihong** [comment]
Correct.

**Comment by KooroshRH** [comment]
Thanks a lot for your help.
