### ISSUE TITLE
The last epoch 

### ISSUE THREAD

**Issue by KooroshRH** [wangkaihong/Unsup_Recycle_GAN#14]
I noticed that the default option for schedulers in options is "Lambda", but based on its formula, it changes the learning rate to zero for the last epoch. Does it have a specific reason?

**Comment by wangkaihong** [comment]
Thanks for bringing this to our attention; we plan to fix the issue. The core idea is not about the optimization process, and we try to keep the optimization procedures close to our baseline, i.e., RecycleGAN, as much as possible for the sake of fair comparison with it, so this is not what we expected.
