### ISSUE TITLE
STC-V2V implementation

### ISSUE THREAD

**Issue by KooroshRH** [wangkaihong/Unsup_Recycle_GAN#15]
Hi,

I hope you are doing well. You mentioned STC-V2V as a state-of-the-art project in your paper and compared your result. I didn't find its implementation in your GitHub repository. Can you provide it to me? I want to use it for comparison in my project.

Thanks

**Comment by wangkaihong** [comment]
We implemented STC-V2V by ourselves based on their paper, but I am unfortunately unable to find the code now since I have no access to my old server now. I believe that it's not technically challenging to reimplement their method, so please give it a try!
