### ISSUE TITLE
VIPER Image size

### ISSUE THREAD

**Issue by SecureSheII** [wangkaihong/Unsup_Recycle_GAN#16]
Hi, thank you for your great work!

I followed your instruction to download VIPER dataset from RecycleGAN's codebase but I found each image is concatenated with its two neighboring frames, i.e. {t-1, t, t+1}, as well as reshaped into 256x256, so every training image from their dataset is of shape 768x256. I am wondering if I need to split every image out of the concatenation and reshape it back to the shape of the original VIPER dataset before running your method. If so, is there any handy script you wrote when you downloaded the VIPER from RecycleGAN's codebase? Thanks again!

**Comment by wangkaihong** [comment]
Hi,

Sorry for didn't make it clearer in the instruction. You don't need concatenating triplets of images (that's for recycle-gan) to run our method. Our UnalignedScaleDataset works directly under the directory of the original images (e.g., unprocessed VIPER), and it takes care of the resizing part. 

Let me know if you have further questions!

**Comment by SecureSheII** [comment]
Thanks for the quick response. I apologize for not asking my question clearly. I am saying that since you mentioned in README that we should download the version of VIPER from RecycleGAN's codebase, which as said contains concatenated images, then I am wondering if you have developed any tools to separate those images back to their original format. Or otherwise, did you download the original VIPER dataset directly and sample those images according to weather, as you mentioned in your Appendix A?

**Comment by SecureSheII** [comment]
Nvm I saw they provided a cycleGAN version of VIPER as well which is just single images.

**Comment by wangkaihong** [comment]
Correct. Preparing datasets with triplets is a must **only if** you are also running recycle-gan as a baseline for comparison.
