### ISSUE TITLE
Pretrained RecycleGAN and CycleGAN

### ISSUE THREAD

**Issue by SecureSheII** [wangkaihong/Unsup_Recycle_GAN#17]
Thank you again for sharing the great work. 

Since authors of RecycleGAN and CycleGAN did not experiment their model for translation between Viper and CityScapes, I am wondering if you have re-trained RecycleGAN and CycleGAN yourself for Viper-to-CityScapes as you compare them with your own method in your paper.  If so, is it possible for you to share these weights as well? I wish I could compare theirs on Viper-to-CityScapes with my latest method too!

**Comment by wangkaihong** [comment]
Yes, I did re-train them and compared them with my model, as presented in the paper, but their weights are not saved, so I cannot provide them now. However, you may easily run Cycle-GAN and Recycle-GAN in our repo by modifying our scripts accordingly, e.g., replacing 'unsup_single' with 'cycle_gan' for Cycle-GAN, or 'reCycle_gan' for Recycle-GAN. Additionally, you may also need to adjust the dataset option like using 'unaligned_triplet_scale' when using Recycle-GAN.

**Comment by SecureSheII** [comment]
Thanks! But in order to retrain RecycleGAN, I do need to rearrange CityScapes into triplets, which means I need to download the ~300GB sequential data rather than the randomly permuted one (~11GB and ~44GB), correct?

**Comment by wangkaihong** [comment]
That is, unfortunately, correct. You need those sequential data to organize your dataset.
