### ISSUE TITLE
Pretrained Models files are not there

### ISSUE THREAD

**Issue by smohitm** [wangkaihong/Unsup_Recycle_GAN#22]
Pretrained Models

Pretrained models in both experiments are available [here](https://drive.google.com/file/d/1-kcLQLBNk5pOMcdAYPnIQAhA-Kg6_jA5/view?usp=sharing).

The above link is mentioned in the repo, but actually when I open there is no pretrained models.
Please share the new link to download the models.

**Comment by wangkaihong** [comment]
Done.

**Comment by smohitm** [comment]
Really Thanks for the prompt reply!
Please upload the FCN models as mentioned in the Evalualtion in read me :
Evaluation

Pretrained FCN model is available [here](https://drive.google.com/file/d/1NmeC32gGoKqitxBax21-FaAKL_cBwwqg/view?usp=sharing). Please place it under .saved_models/.

In this above these models are also not available.
Please share the new link to download these too. :)
