### ISSUE TITLE
for face2face translation task

### ISSUE THREAD

**Issue by ruanjiyang** [wangkaihong/Unsup_Recycle_GAN#3]
Dear wangkaihong

What a nice job!  just one question: for face2face translation task. should I follow the way of "Video-to-Label Experiment"? right? 

Thanks!

in Chinese:
感谢你工作。 我想要尝试face2face translation 任务，请问，我是否按照"Video-to-Label Experiment"的方法来做，对么？  在数据集A 和B中，每个图片都只需要1张脸（而不是连续三帧的脸，并排放在一起）。 请问我的理解正确么？谢谢！

**Comment by wangkaihong** [comment]
Hi,

Thanks for your interest in our work! Yes, for the face-to-face experiment you may just follow the configurations as in the Video-to-labels experiments, but you don't need the video domain regularization suppression as it's not asymmetric one-to-many mapping.

**Comment by ruanjiyang** [comment]
Thanks for your rapid response.  sorry, could you please explain how to "don't need the video domain regularization suppression"?  thanks again.

**Comment by wangkaihong** [comment]
Please refer to Appendix A for further details about the video domain regularization suppression.
