### ISSUE TITLE
output

### ISSUE THREAD

**Issue by lx123-j** [wangkaihong/Unsup_Recycle_GAN#4]
Hi, after read your code I want to figure out what is the output of your code? a lot of images? Chose two images for random, then just output them? But not a video?

**Comment by wangkaihong** [comment]
Thanks for you interest in our work!

When you run the test command, this line will save each processed image in the designated set of your data in a folder and that would be the output.
https://github.com/wangkaihong/Unsup_Recycle_GAN/blob/master/test.py#L36
