### ISSUE TITLE
optical flow

### ISSUE THREAD

**Issue by lx123-j** [wangkaihong/Unsup_Recycle_GAN#6]
Your code is fantastic, but there is a part I hardly understand. In the GenerateFakeFlow, the input is first_frame. It's that mean the optical flow only uses a picture to generate? 
Sorry, I learned about this project lately so there are so many questions.

**Comment by wangkaihong** [comment]
Yes, as our paper has stated, one of the advantages of our method is that we can train the model with any static frame instead of a series of temporally adjacent frames, which makes it easier and computationally cheaper.

**Comment by lx123-j** [comment]
Thank you for the answer, but the optical flow is generated from the static frame, why do we need this?
