### ISSUE TITLE
Image Resolution of video-to-label / label-to-video

### ISSUE THREAD

**Issue by indigopyj** [wangkaihong/Unsup_Recycle_GAN#9]
Hi, I have some questions about input resolution of video-to-label and label-to-video tasks.

I know that you used Viper dataset which has images with a resolution of 1920 x 1080. 

However, according to your test command in README, 
```
python train.py --dataroot path/to/data/ --model unsup_single --dataset_mode unaligned_scale --name v2l_experiment --loadSizeW 286 --loadSizeH 286 --resize_mode rectangle --fineSizeW 256 --fineSizeH 256 --crop_mode rectangle --which_model_netG resnet_6blocks --no_dropout --pool_size 0 --lambda_spa_unsup_A 10 --lambda_spa_unsup_B 0 --lambda_unsup_cycle_A 0 --lambda_unsup_cycle_B 10 --lambda_cycle_A 10 --lambda_cycle_B 10 --lambda_content_A 0 --lambda_content_B 0 --batchSize 1 --noise_level 0.001  --niter_decay 0 --niter 5
python test.py --dataroot path/to/data/ --model unsup_single --dataset_mode unaligned_scale --name v2l_experiment --loadSizeW 256 --loadSizeH 256 --resize_mode rectangle --fineSizeW 256 --fineSizeH 256 --crop_mode none --which_model_netG resnet_6blocks --no_dropout --which_epoch 5
```

you resize images into 256 x 256 resolution for both training and test.

I thought you used the rectangular image(256x512) for v2l/l2v tasks because of Fig.5 in your paper.

Could you please let me know exactly what resolution of image you used for v2l/l2v tasks?

**Comment by wangkaihong** [comment]
Hi,

We followed the baseline's configuration and set the resolution to 256x256 simply for the sake of fair comparison with, e.g., Recycle-GAN. If you want to visualize it, you can just resize the output to any desired resolution, like 512x256, or you can also train and test in that resolution directly.
